### ISSUE TITLE
Mark as done button is not visible

### ISSUE THREAD

**Issue by Dimitrispant** [success4all-eu/learning-platform#1]
The button mark as done in the activities is not visible. 

1. Go to a selected course 
2. Click on 'Add an activity or resource'
3. Create a Learning Resource (e.g. a file)
4. Enable Activity completion to manual
5. See error

The button should be visible. Seems to be a CSS issue

**Screenshots**
![image](https://user-images.githubusercontent.com/13375110/170998501-753fbd46-b615-45b2-a95f-3cbd024bd1d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Edge 
 - Version 101.0.1210.53 (Official build) (64-bit)

**Comment by michzimny** [comment]
@Dimitrispant, thanks for reporting!

The button is disabled for you and thus (almost) invisible.

The cause is that you are a teacher and the course creator, and so you cannot mark completion in your course. If you assign the student role in that course to your account (in "Participants"), then the button becomes visible and clickable. It will be also visible for your students.
